version: "3"

networks:
  udemyMongoStudy:
    driver: bridge

services:
  mongoDB:
    image: mongo
    container_name: springMongoDB
    hostname: springMongoDB
    networks:
      - udemyMongoStudy
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/data:/data"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    hostname: mongo_express
    networks:
      - udemyMongoStudy
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=springMongoDB
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=admin